### ISSUE TITLE
copy to clipboard support

### ISSUE THREAD

**Issue by ayushhroyy** [christofferaakre/flameshot-ocr#1]
hey, it currently does not work on arch linux and gives error *Tesseract couldn't load any languages!* + is copy to clipboard support something we could expect in the future?

**Comment by christofferaakre** [comment]
> hey, it currently does not work on arch linux and gives error _Tesseract couldn't load any languages!_ + is copy to clipboard support something we could expect in the future?

@ayushhroyy
Which language option are you passing to the script?
 Can you try running tesseract manually from the command line?
i.e. `tesseract my_picture.png output.txt -l my_language`
Then `cat output.txt`. Assuming you still get the same error message, try running
`locate *.traineddata`. You should see some output like this: 
```console
/usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata
/usr/share/tesseract-ocr/4.00/tessdata/jpn.traineddata
/usr/share/tesseract-ocr/4.00/tessdata/jpn_vert.traineddata
/usr/share/tesseract-ocr/4.00/tessdata/osd.traineddata
```
Try running tesseract with one of the language options listed there, so in my example I could try with `-l eng` for example. If that works, then probably you don't have the right `.traineddata` file for some reason. You can find them here: https://github.com/tesseract-ocr/tessdata
Just download the one you need, and place it in the same directory as the other `.traineddata` files (most likely `/usr/share/tesseract-ocr/4.00/tessdata`)

As for your question about copy to clipboard support, it already does that! The reason it is not copying anything to your clipboard is presumably that tesseract is failing. It should copy it to your clipboard once you get it working. 
Let me know if this helps or not :)
